# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_finished_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='finished_date',
            new_name='completed_date',
        ),
    ]
