# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20170622_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed_date',
            new_name='completion_date',
        ),
    ]
